/*
 * Copyright (c) 2026 Kenneth Stott
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE-BSL.txt file in the root directory of this source tree.
 *
 * NOTICE: Use of this software for training artificial intelligence or
 * machine learning models is strictly prohibited without explicit written
 * permission from the copyright holder.
 */
package org.apache.calcite.adapter.govdata.ref;

import org.apache.calcite.adapter.file.etl.RequestContext;
import org.apache.calcite.adapter.file.etl.ResponseTransformer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.InputStream;

/**
 * Builds the {@code ref.countries} crosswalk from the live Census "Schedule C"
 * country-code list, enriched with the stable ISO "spine" bundled as a
 * classpath resource.
 *
 * <p>Country identity is fragmented across the govdata datasets: the trade
 * tables ({@code econ.trade_by_state} / {@code trade_exports} / {@code trade_imports})
 * key on the Census 4-digit country code; {@code econ.world_indicators} keys on
 * ISO alpha-3; the BEA tables ({@code ita_data} / {@code fdi_*}) carry only an
 * area <em>name</em>. This transformer produces one row per country that carries
 * all of those keys so the datasets become mutually joinable.
 *
 * <h3>Inputs</h3>
 * <ul>
 *   <li><b>HTTP source (live, freshness-gated):</b> Census Schedule C
 *       {@code country.txt} — a pipe-delimited {@code code | name | ISO-alpha2}
 *       list. This is the authoritative source for {@code census_cty_code} and
 *       supplies the clean, trade-oriented {@code country_name}.</li>
 *   <li><b>Bundled resource (stable, checked in):</b>
 *       {@code /ref/country-enrichment.json} — keyed by ISO alpha-2, carrying
 *       alpha-3, numeric, FIPS, M49 region/subregion/continent, and currency.
 *       Regenerated by {@code scripts/build-countries-ref-resources.py}.</li>
 * </ul>
 *
 * <h3>Canonical Output Schema</h3>
 * <pre>
 * - census_cty_code:     STRING  - Census 4-digit country code (FK target for trade tables)
 * - iso_alpha2:          STRING  - ISO 3166-1 alpha-2
 * - iso_alpha3:          STRING  - ISO 3166-1 alpha-3
 * - iso_numeric:         STRING  - ISO 3166-1 numeric
 * - fips_code:           STRING  - FIPS 10-4 country code
 * - country_name:        STRING  - Census display name (clean short form)
 * - official_name:       STRING  - ISO English official name
 * - bea_area_name:       STRING  - country_name with any parenthetical stripped
 *                                  (best-effort join key for BEA area_or_country)
 * - currency_code:       STRING  - ISO 4217 currency alphabetic code
 * - region:              STRING  - M49 region
 * - subregion:           STRING  - M49 sub-region
 * - intermediate_region: STRING  - M49 intermediate region
 * - continent:           STRING  - Continent code
 * - is_aggregate:        BOOLEAN - true when the Census row carries no ISO code
 *                                  (grouping/area rather than a single country)
 * </pre>
 *
 * @see ResponseTransformer
 */
public class CountriesReferenceTransformer implements ResponseTransformer {

  private static final Logger LOGGER =
      LoggerFactory.getLogger(CountriesReferenceTransformer.class);
  private static final ObjectMapper MAPPER = new ObjectMapper();
  private static final String ENRICHMENT_RESOURCE = "/ref/country-enrichment.json";

  /** Lazily-loaded, immutable after first read. */
  private static volatile JsonNode enrichment;

  private static JsonNode enrichment() {
    JsonNode local = enrichment;
    if (local == null) {
      synchronized (CountriesReferenceTransformer.class) {
        local = enrichment;
        if (local == null) {
          try (InputStream in =
              CountriesReferenceTransformer.class.getResourceAsStream(ENRICHMENT_RESOURCE)) {
            if (in == null) {
              throw new IllegalStateException(
                  "Missing bundled resource " + ENRICHMENT_RESOURCE
                      + " (run scripts/build-countries-ref-resources.py)");
            }
            local = MAPPER.readTree(in);
            enrichment = local;
          } catch (Exception e) {
            throw new RuntimeException(
                "Failed to load " + ENRICHMENT_RESOURCE + ": " + e.getMessage(), e);
          }
        }
      }
    }
    return local;
  }

  @Override public String transform(String response, RequestContext context) {
    if (response == null || response.isEmpty()) {
      LOGGER.warn("Countries: empty Census response for {}", context.getUrl());
      return "[]";
    }

    JsonNode spine = enrichment();
    ArrayNode out = MAPPER.createArrayNode();

    String[] lines = response.split("\\r?\\n");
    for (int i = 0; i < lines.length; i++) {
      String line = lines[i];
      // Data rows are "code | name | ISO"; header and dashed-separator lines
      // have no pipe or a non-numeric first field and are skipped.
      int firstBar = line.indexOf('|');
      if (firstBar < 0) {
        continue;
      }
      String[] parts = line.split("\\|", -1);
      if (parts.length < 2) {
        continue;
      }
      String code = parts[0].trim();
      if (!code.matches("\\d{3,4}")) {
        continue;
      }
      String name = parts[1].trim();
      String iso2 = parts.length >= 3 ? parts[2].trim() : "";

      ObjectNode row = MAPPER.createObjectNode();
      row.put("census_cty_code", code);
      putOrNull(row, "iso_alpha2", iso2);
      row.put("country_name", name.isEmpty() ? null : name);
      putOrNull(row, "bea_area_name", stripParenthetical(name));
      row.put("is_aggregate", iso2.isEmpty());

      JsonNode e = iso2.isEmpty() ? null : spine.get(iso2);
      row.set("iso_alpha3", textOrNull(e, "iso_alpha3"));
      row.set("iso_numeric", textOrNull(e, "iso_numeric"));
      row.set("fips_code", textOrNull(e, "fips"));
      row.set("official_name", textOrNull(e, "official_name"));
      row.set("currency_code", textOrNull(e, "currency_code"));
      row.set("region", textOrNull(e, "region"));
      row.set("subregion", textOrNull(e, "subregion"));
      row.set("intermediate_region", textOrNull(e, "intermediate_region"));
      row.set("continent", textOrNull(e, "continent"));

      out.add(row);
    }

    LOGGER.debug("Countries: built {} rows from Census Schedule C", out.size());
    return out.toString();
  }

  /** Strips a trailing parenthetical, e.g. "South Korea (Republic of Korea)" -> "South Korea". */
  private static String stripParenthetical(String name) {
    if (name == null) {
      return null;
    }
    return name.replaceAll("\\s*\\([^)]*\\)\\s*$", "").trim();
  }

  private static void putOrNull(ObjectNode row, String field, String value) {
    if (value == null || value.isEmpty()) {
      row.putNull(field);
    } else {
      row.put(field, value);
    }
  }

  /** Returns the string field from the enrichment node, or a JSON null node. */
  private static JsonNode textOrNull(JsonNode enrichmentNode, String field) {
    if (enrichmentNode == null) {
      return MAPPER.nullNode();
    }
    JsonNode v = enrichmentNode.get(field);
    return (v == null || v.isNull()) ? MAPPER.nullNode() : v;
  }
}
