#!/usr/bin/env python3
"""Build bundled reference-data YAML resources for the govdata `ref` schema.

Fetches authoritative sources and emits classpath resources consumed by the
ref-schema tables via `source.type: constants`. Mirrors the intent of
build-countries-ref-resources.py. NO reference row is hand-authored here.

Outputs:
  ref/naics-codes.yaml     Census 2022 NAICS 2-6 digit codes + titles
  ref/sic-codes.yaml       SEC EDGAR Standard Industrial Classification list
  ref/currency-codes.yaml  ISO 4217 active currencies
  geo/zcta-ref.yaml        Census ZCTA gazetteer (non-vintaged ZIP FK spine)

Run:  python3 govdata/scripts/build-refs.py
"""
import csv, html, os, re, sys, urllib.request, zipfile
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(HERE, "..", "src", "main", "resources"))
OUT = os.path.join(RES, "ref")
NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " \
     "(KHTML, like Gecko) Chrome/120 Safari/537.36"

NAICS_URL = "https://www.census.gov/naics/2022NAICS/2-6%20digit_2022_Codes.xlsx"
# NAICS revises in ~5-year editions. Only 2017+ are published at this Census URL layout;
# 2002/2007/2012 live at different archived paths — add them here once sourced.
NAICS_EDITIONS = [2017, 2022]
CURR_URL = "https://raw.githubusercontent.com/datasets/currency-codes/main/data/codes-all.csv"
SIC_URL = "https://www.sec.gov/info/edgar/siccodes.htm"
# archive.org fallback (SEC edge blocks datacenter IPs with 403)
SIC_FALLBACK = "https://web.archive.org/web/2id_/" + SIC_URL
ZCTA_URL = ("https://www2.census.gov/geo/docs/maps-data/data/gazetteer/"
            "2023_Gazetteer/2023_Gaz_zcta_national.zip")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept-Encoding": "identity"})
    data = urllib.request.urlopen(req, timeout=60).read()
    if data[:2] == b"\x1f\x8b":  # gzip magic (archive.org serves stored gzip bytes)
        import gzip
        data = gzip.decompress(data)
    return data


def fetch_text(url):
    return fetch(url).decode("utf-8", "replace")


def yq(s):
    return '"' + (s or "").strip().replace('"', '\\"') + '"'


def write_yaml(name, root_key, rows, cols, header, schema="ref"):
    path = os.path.join(RES, schema, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# GENERATED by scripts/build-refs.py -- do not hand-edit.\n")
        f.write("# " + header + "\n")
        f.write(root_key + ":\n")
        for r in rows:
            first = True
            for c in cols:
                v = r.get(c)
                lead = "  - " if first else "    "
                first = False
                if v is None or v == "":
                    f.write(lead + c + ": null\n")
                elif isinstance(v, bool):
                    f.write(lead + c + ": " + ("true" if v else "false") + "\n")
                elif isinstance(v, (int, float)):
                    f.write(lead + c + ": " + repr(v) + "\n")
                else:
                    f.write(lead + c + ": " + yq(v) + "\n")
    print("wrote %s (%d rows)" % (path, len(rows)))


def _parse_naics(raw):
    """Parse a Census NAICS '2-6 digit Codes' xlsx into [{naics_code, naics_title, level}]."""
    z = zipfile.ZipFile(__import__("io").BytesIO(raw))
    shared = []
    if "xl/sharedStrings.xml" in z.namelist():
        st = ET.fromstring(z.read("xl/sharedStrings.xml"))
        for si in st.findall(NS + "si"):
            shared.append("".join(t.text or "" for t in si.iter(NS + "t")))
    sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    code_re = re.compile(r"^\d{2,6}(-\d{2})?$")
    out, seen = [], set()
    for row in sheet.iter(NS + "row"):
        cells = {}
        for c in row.findall(NS + "c"):
            v = c.find(NS + "v")
            if v is None:
                continue
            col = re.match(r"[A-Z]+", c.get("r")).group()
            cells[col] = shared[int(v.text)] if c.get("t") == "s" else v.text
        code = title = None
        for col in sorted(cells):
            val = (cells[col] or "").strip()
            if code is None and code_re.match(val):
                code = val
            elif code is not None and title is None and val and not val.isdigit():
                title = val
        if code and title and code not in seen:
            seen.add(code)
            out.append({"naics_code": code,
                        "naics_title": title.rstrip("T ").strip(),
                        "level": len(code.split("-")[0])})
    return out


def build_naics():
    write_yaml("naics-codes.yaml", "naics", _parse_naics(fetch(NAICS_URL)),
               ["naics_code", "naics_title", "level"],
               "Census 2022 NAICS 2-6 digit industry classification.")


def build_naics_vintage():
    """Multi-edition NAICS: one row per code PER vintage (edition year). Consumers join a
    fact to the edition in effect for its period via ref.naics_vintage_map."""
    rows = []
    for year in NAICS_EDITIONS:
        url = "https://www.census.gov/naics/%dNAICS/2-6%%20digit_%d_Codes.xlsx" % (year, year)
        ed = _parse_naics(fetch(url))
        for r in ed:
            rows.append({"vintage": year, "naics_code": r["naics_code"],
                         "naics_title": r["naics_title"], "level": r["level"]})
        print("  naics vintage %d: %d codes" % (year, len(ed)))
    write_yaml("naics-vintage-codes.yaml", "naics_vintage", rows,
               ["vintage", "naics_code", "naics_title", "level"],
               "Census NAICS editions " + ",".join(str(y) for y in NAICS_EDITIONS)
               + " (2-6 digit), one row per code per vintage.")


def build_naics_vintage_map():
    """Data-year -> applicable NAICS edition. Edition E is in effect for years [E, nextE-1];
    years before the earliest loaded edition use that earliest edition (documented fallback)."""
    eds = sorted(NAICS_EDITIONS)
    rows = []
    for y in range(2010, 2028):
        v = eds[0]
        for e in eds:
            if y >= e:
                v = e
        rows.append({"data_year": y, "naics_vintage": v})
    write_yaml("naics-vintage-map.yaml", "naics_vintage_map", rows,
               ["data_year", "naics_vintage"],
               "Data-year -> NAICS edition in effect (loaded editions: "
               + ",".join(str(e) for e in eds) + "; pre-earliest years use the earliest).")


def build_currency():
    text = fetch_text(CURR_URL)
    seen = {}
    for r in csv.DictReader(text.splitlines()):
        code = (r.get("AlphabeticCode") or "").strip()
        if not code or (r.get("WithdrawalDate") or "").strip() or code in seen:
            continue
        minor = (r.get("MinorUnit") or "").strip()
        seen[code] = {"currency_code": code,
                      "currency_name": (r.get("Currency") or "").strip(),
                      "numeric_code": (r.get("NumericCode") or "").strip(),
                      "minor_unit": int(minor) if minor.isdigit() else None}
    rows = [seen[k] for k in sorted(seen)]
    write_yaml("currency-codes.yaml", "currencies", rows,
               ["currency_code", "currency_name", "numeric_code", "minor_unit"],
               "ISO 4217 active currencies (datasets/currency-codes).")


def build_sic():
    try:
        t = fetch_text(SIC_URL)
        if "<td" not in t.lower():
            raise ValueError("no table")
    except Exception as e:
        print("SIC primary failed (%s); using archive.org fallback" % e)
        t = fetch_text(SIC_FALLBACK)
    out, seen = [], set()
    for tr in re.findall(r"<tr[^>]*>(.*?)</tr>", t, re.S | re.I):
        cells = [html.unescape(re.sub(r"<[^>]+>", "", c)).strip()
                 for c in re.findall(r"<td[^>]*>(.*?)</td>", tr, re.S | re.I)]
        if len(cells) < 3 or not re.match(r"^\d{2,4}$", cells[0]):
            continue
        code = cells[0].zfill(4)
        if code in seen:
            continue
        seen.add(code)
        out.append({"sic_code": code, "ad_office": cells[1], "industry_title": cells[2]})
    write_yaml("sic-codes.yaml", "sic", out,
               ["sic_code", "ad_office", "industry_title"],
               "SEC EDGAR Standard Industrial Classification code list.")


def build_zcta():
    import io
    raw = fetch(ZCTA_URL)
    z = zipfile.ZipFile(io.BytesIO(raw))
    name = [n for n in z.namelist() if n.lower().endswith(".txt")][0]
    text = z.read(name).decode("latin-1")
    lines = text.splitlines()
    hdr = [h.strip() for h in lines[0].split("\t")]
    idx = {h: i for i, h in enumerate(hdr)}
    out, seen = [], set()
    for ln in lines[1:]:
        if not ln.strip():
            continue
        f = ln.split("\t")
        zcta = f[idx["GEOID"]].strip()
        if not zcta or zcta in seen:
            continue
        seen.add(zcta)

        def num(col):
            v = f[idx[col]].strip()
            try:
                return float(v)
            except ValueError:
                return None
        out.append({"zcta": zcta,
                    "land_area_sqmi": num("ALAND_SQMI"),
                    "water_area_sqmi": num("AWATER_SQMI"),
                    "latitude": num("INTPTLAT"),
                    "longitude": num("INTPTLONG")})
    write_yaml("zcta-ref.yaml", "zctas", out,
               ["zcta", "land_area_sqmi", "water_area_sqmi", "latitude", "longitude"],
               "Census 2020-vintage ZCTAs (2023 national gazetteer) — non-vintaged ZIP FK spine.",
               schema="geo")


if __name__ == "__main__":
    build_naics()
    build_naics_vintage()
    build_naics_vintage_map()
    build_currency()
    build_sic()
    build_zcta()
    print("done")
