/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.adapter.file;

import org.apache.calcite.util.Source;
import org.apache.calcite.util.Sources;

import org.jsoup.select.Elements;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for FileReaderV2 covering HTML table parsing,
 * iterator functionality, and FileReaderIterator inner class.
 */
@Tag("unit")
public class FileReaderV2CoverageTest {

  @TempDir
  java.nio.file.Path tempDir;

  private File createHtmlFile(String content) throws IOException {
    File file = new File(tempDir.toFile(), "test.html");
    try (FileWriter writer = new FileWriter(file)) {
      writer.write(content);
    }
    return file;
  }

  @Test void testBasicTableParsing() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>Name</th><th>Age</th></tr>"
        + "<tr><td>Alice</td><td>30</td></tr>"
        + "<tr><td>Bob</td><td>25</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Iterator<Elements> iter = reader.iterator();
    assertNotNull(iter);

    List<Elements> rows = new ArrayList<>();
    while (iter.hasNext()) {
      rows.add(iter.next());
    }

    // Should have data rows (headers consumed internally)
    assertTrue(rows.size() >= 2);
    reader.close();
  }

  @Test void testGetHeadings() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>First</th><th>Second</th><th>Third</th></tr>"
        + "<tr><td>a</td><td>b</td><td>c</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Elements headings = reader.getHeadings();
    assertNotNull(headings);
    assertEquals(3, headings.size());
    assertEquals("First", headings.get(0).text());
    assertEquals("Second", headings.get(1).text());
    assertEquals("Third", headings.get(2).text());

    reader.close();
  }

  @Test void testGetHeadingsAutoGenerated() throws IOException {
    // Table without th elements - should auto-generate headings
    String html = "<html><body><table>"
        + "<tr><td>a</td><td>b</td><td>c</td></tr>"
        + "<tr><td>d</td><td>e</td><td>f</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Elements headings = reader.getHeadings();
    assertNotNull(headings);
    assertEquals(3, headings.size());
    // Auto-generated headings should be col0, col1, col2
    assertEquals("col0", headings.get(0).text());
    assertEquals("col1", headings.get(1).text());
    assertEquals("col2", headings.get(2).text());

    reader.close();
  }

  @Test void testWithSelector() throws IOException {
    String html = "<html><body>"
        + "<table id='main'>"
        + "<tr><th>Name</th></tr>"
        + "<tr><td>Alice</td></tr>"
        + "</table>"
        + "<table id='other'>"
        + "<tr><th>Value</th></tr>"
        + "<tr><td>42</td></tr>"
        + "</table>"
        + "</body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source, "table#main");

    Elements headings = reader.getHeadings();
    assertNotNull(headings);
    assertEquals(1, headings.size());
    assertEquals("Name", headings.get(0).text());

    reader.close();
  }

  @Test void testWithSelectorAndIndex() throws IOException {
    String html = "<html><body>"
        + "<table class='data'>"
        + "<tr><th>A</th></tr>"
        + "<tr><td>1</td></tr>"
        + "</table>"
        + "<table class='data'>"
        + "<tr><th>B</th></tr>"
        + "<tr><td>2</td></tr>"
        + "</table>"
        + "</body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    // Select the second table with class='data'
    FileReaderV2 reader = new FileReaderV2(source, "table.data", 1);

    Elements headings = reader.getHeadings();
    assertNotNull(headings);
    assertEquals(1, headings.size());
    assertEquals("B", headings.get(0).text());

    reader.close();
  }

  @Test void testBestTableSelection() throws IOException {
    // When no selector, should pick the largest table
    String html = "<html><body>"
        + "<table>"
        + "<tr><th>X</th></tr>"
        + "<tr><td>1</td></tr>"
        + "</table>"
        + "<table>"
        + "<tr><th>A</th><th>B</th><th>C</th></tr>"
        + "<tr><td>1</td><td>2</td><td>3</td></tr>"
        + "<tr><td>4</td><td>5</td><td>6</td></tr>"
        + "</table>"
        + "</body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Elements headings = reader.getHeadings();
    assertNotNull(headings);
    // Should pick the larger table (3 columns, 2 data rows)
    assertEquals(3, headings.size());

    reader.close();
  }

  @Test void testNoTablesThrowsException() throws IOException {
    String html = "<html><body><p>No tables here</p></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    assertThrows(RuntimeException.class, () -> reader.iterator());
    reader.close();
  }

  @Test void testRefresh() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>Name</th></tr>"
        + "<tr><td>Alice</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    // First read
    Elements headings1 = reader.getHeadings();
    assertNotNull(headings1);

    // Refresh should re-read the file
    try {
      reader.refresh();
    } catch (FileReaderException e) {
      throw new RuntimeException(e);
    }

    // After refresh, headings are reset and re-read on next call
    Elements headings2 = reader.getHeadings();
    assertNotNull(headings2);
    assertEquals(headings1.size(), headings2.size());

    reader.close();
  }

  @Test void testFileReaderIteratorRemoveThrows() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>Name</th></tr>"
        + "<tr><td>Alice</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Iterator<Elements> iter = reader.iterator();
    assertThrows(UnsupportedOperationException.class, () -> iter.remove());

    reader.close();
  }

  @Test void testIteratorMultipleRows() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>ID</th><th>Value</th></tr>"
        + "<tr><td>1</td><td>A</td></tr>"
        + "<tr><td>2</td><td>B</td></tr>"
        + "<tr><td>3</td><td>C</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    Iterator<Elements> iter = reader.iterator();
    int count = 0;
    while (iter.hasNext()) {
      Elements row = iter.next();
      assertNotNull(row);
      count++;
    }
    // Should have data rows (header row is consumed)
    assertTrue(count >= 3);

    reader.close();
  }

  @Test void testSelectorNotTableThrowsException() throws IOException {
    String html = "<html><body>"
        + "<div id='not-table'>Not a table</div>"
        + "</body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source, "div#not-table");

    assertThrows(RuntimeException.class, () -> reader.iterator());
    reader.close();
  }

  @Test void testCloseIsIdempotent() throws IOException {
    String html = "<html><body><table>"
        + "<tr><th>Name</th></tr>"
        + "<tr><td>Alice</td></tr>"
        + "</table></body></html>";

    File file = createHtmlFile(html);
    Source source = Sources.of(file);
    FileReaderV2 reader = new FileReaderV2(source);

    reader.close();
    reader.close(); // Should not throw
  }
}
