#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Surgical text-level editor for one table's `observedCoverage:` block in a govdata
# schema YAML. Deliberately does NOT parse+re-dump the file with a YAML library — these
# files are hand-authored with heavy prose comments and folded scalars; a round-trip
# through PyYAML's dumper reformats the whole file and destroys that. Instead this finds
# the target table's `pattern:` line by exact text match and inserts/replaces a single,
# clearly-marked block immediately after it, leaving every other byte in the file alone.
#
# Exit codes: 0 = updated (or already up to date), 3 = table has no `pattern:` line (no
# year partition to report on — not an error, just nothing to do), 1 = table not found /
# other error.

import argparse
import re
import sys

MARKER = "# auto-generated by update-coverage-metadata.sh — do not hand-edit"


def build_block(min_year, max_year, distinct_years, contiguous, years, row_count, checked_at):
    lines = [f"    observedCoverage:  {MARKER}"]
    lines.append(f"      minYear: {min_year}")
    lines.append(f"      maxYear: {max_year}")
    lines.append(f"      distinctYears: {distinct_years}")
    lines.append(f"      contiguous: {'true' if contiguous else 'false'}")
    if not contiguous and years:
        year_list = ", ".join(str(y) for y in years)
        lines.append(f"      years: [{year_list}]")
    lines.append(f"      rowCount: {row_count}")
    lines.append(f"      checkedAt: \"{checked_at}\"")
    return lines


def indent_of(line):
    return len(line) - len(line.lstrip(" "))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--file", required=True)
    p.add_argument("--table", required=True)
    p.add_argument("--min-year", required=True, type=int)
    p.add_argument("--max-year", required=True, type=int)
    p.add_argument("--distinct-years", required=True, type=int)
    p.add_argument("--contiguous", required=True, choices=["true", "false"])
    p.add_argument("--years", default="", help="comma-separated explicit year list, required when --contiguous=false")
    p.add_argument("--row-count", required=True, type=int)
    p.add_argument("--checked-at", required=True)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    with open(args.file, "r", encoding="utf-8") as f:
        lines = f.read().split("\n")

    name_re = re.compile(r"^  - name: " + re.escape(args.table) + r"\s*$")
    next_item_re = re.compile(r"^  - name: ")
    pattern_re = re.compile(r"^    pattern:\s")

    start = None
    for i, line in enumerate(lines):
        if name_re.match(line):
            start = i
            break
    if start is None:
        print(f"ERROR: no '- name: {args.table}' entry found in {args.file}", file=sys.stderr)
        sys.exit(1)

    # Bound the search for this table's own `pattern:` line at the next sibling entry.
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if next_item_re.match(lines[i]):
            end = i
            break

    pattern_idx = None
    for i in range(start + 1, end):
        if pattern_re.match(lines[i]):
            pattern_idx = i
            break

    if pattern_idx is None:
        print(f"SKIP: {args.table} has no 'pattern:' line — no year partition to report on", file=sys.stderr)
        sys.exit(3)

    years = [int(y) for y in args.years.split(",") if y.strip()] if args.years else []
    new_block = build_block(
        args.min_year, args.max_year, args.distinct_years,
        args.contiguous == "true", years, args.row_count, args.checked_at,
    )

    # Remove an existing observedCoverage block immediately after `pattern:`, if present —
    # identified by our own marker so we never touch a differently-purposed key.
    remove_end = pattern_idx + 1
    if remove_end < len(lines) and MARKER in lines[remove_end]:
        j = remove_end + 1
        while j < len(lines) and (lines[j].strip() == "" or indent_of(lines[j]) > 4):
            # A blank line immediately inside our own block never occurs (we don't emit
            # one), so stop at the first blank line too rather than eating unrelated
            # trailing blank lines that separate this table from the next.
            if lines[j].strip() == "":
                break
            j += 1
        old_block = lines[remove_end:j]
        if old_block == new_block:
            print(f"UNCHANGED: {args.table}")
            sys.exit(0)
        lines[remove_end:j] = []

    lines[pattern_idx + 1:pattern_idx + 1] = new_block

    if args.dry_run:
        print(f"DRY RUN — would update {args.table} in {args.file}:")
        print("\n".join(new_block))
        sys.exit(0)

    with open(args.file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"UPDATED: {args.table}")


if __name__ == "__main__":
    main()
