#!/usr/bin/env python3
"""Writes cloud-ops/src/test/resources/local-test.properties from the CLOUDOPS_* variables in
govdata/.env.prod, so the live tests run against the same credentials the env file documents.

A cloud is written only when all of its required variables are set; the others are left out,
and the tests skip them.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ENV_FILE = ROOT / "govdata" / ".env.prod"
TARGET = ROOT / "cloud-ops" / "src" / "test" / "resources" / "local-test.properties"

# property -> (env variable, required)
CLOUDS = {
    "azure": {
        "azure.tenantId": ("CLOUDOPS_AZURE_TENANT_ID", True),
        "azure.clientId": ("CLOUDOPS_AZURE_CLIENT_ID", True),
        "azure.clientSecret": ("CLOUDOPS_AZURE_CLIENT_SECRET", True),
        "azure.subscriptionIds": ("CLOUDOPS_AZURE_SUBSCRIPTION_IDS", True),
    },
    "aws": {
        "aws.accessKeyId": ("CLOUDOPS_AWS_ACCESS_KEY_ID", True),
        "aws.secretAccessKey": ("CLOUDOPS_AWS_SECRET_ACCESS_KEY", True),
        "aws.accountIds": ("CLOUDOPS_AWS_ACCOUNT_IDS", True),
        "aws.roleArn": ("CLOUDOPS_AWS_ROLE_ARN", False),
    },
    "gcp": {
        "gcp.credentialsPath": ("CLOUDOPS_GCP_CREDENTIALS_PATH", True),
        "gcp.projectIds": ("CLOUDOPS_GCP_PROJECT_IDS", True),
    },
}


def read_env(path):
    env = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if line.startswith("export "):
            line = line[len("export "):].strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        env[key.strip()] = value
    return env


def main():
    env = read_env(ENV_FILE)
    lines = ["# Generated by cloud-ops/scripts/write-local-test-properties.py from govdata/.env.prod",
             "# Do not commit."]
    written = []
    for cloud, properties in CLOUDS.items():
        missing = [var for var, required in properties.values() if required and not env.get(var)]
        if missing:
            print(f"{cloud}: skipped, blank: {', '.join(missing)}")
            continue
        for prop, (var, _) in properties.items():
            if env.get(var):
                lines.append(f"{prop}={env[var]}")
        written.append(cloud)
    if not written:
        sys.exit("no cloud has all of its CLOUDOPS_* variables set in " + str(ENV_FILE))
    TARGET.write_text("\n".join(lines) + "\n")
    TARGET.chmod(0o600)
    print(f"wrote {TARGET.relative_to(ROOT)} for: {', '.join(written)}")


if __name__ == "__main__":
    main()
